### ISSUE TITLE
Kept failing pushes

### ISSUE THREAD

**Issue by yifeili98** [FHDA/DBImport#14]
I kept receiving the following error when I tried to push:

```
some sort of pushing code
Username for 'https://github.com': ***
Password for 'https://yifeili98@github.com': ***
husky > pre-push (node v10.16.3)
=================== test session starts=====================
platform linux2 -- Python 2.7.15+, pytest-4.6.5, py-1.8.0, pluggy-0.13.0
rootdir: /home/zhirezhixin/Personal_Workflow/FHDA
collected 1 item

tests/00_empty_test.py .                                                                                         [100%]

====================== 1 passed in 1.13 seconds ======================
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master

husky > pre-push hook failed (add --no-verify to bypass)
error: failed to push some refs to 'https://github.com/yifeili98/DBImport'
```

The push method I tried:
`git push origin master  

git push --set-upstream origin master  

git push -f --set-upstream origin master  

git push master --force  
`

The method succeeded::smile::
`git push origin master --no-verify`

**Comment by kis87988** [comment]
weird. so what exactly error message did you get?

**Comment by yifeili98** [comment]
I kept getting 
```
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master
```
Even when I used the "--set-upstream"

**Comment by kis87988** [comment]
weird.. need to dig into the detail. The info is not enough.

**Comment by yifeili98** [comment]
LOL nvm
Somehow somewhat I tried to git init in a new folder, pulled my master repo, apply the changes and pushed again, it worked.
I think I messed up with the previous broken git folder somehow and then I kept failing the pre-push hook
